version: "3.8"

services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
      target: development
    volumes:
      - ./server:/alar-users/src/app
      - /alar-users/src/app/node_modules
    command: npm run start:debug
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: jwt_secret
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229


  webclient:
    build:
      dockerfile: Dockerfile
      context: ./web-client
      target: development
    command: npm run start
    volumes:
      - ./web-client:/alar-users/web-client/src/app
      - /alar-users/web-client/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - server

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
